# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  SERVER_BINARY: cmd/server/server.exe
  AGENT_BINARY: cmd/agent/agent.exe
  LOG_DIR: logs
  TEMP_FILE: tempfile

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -f {{.SERVER_BINARY}}
      - rm -f {{.AGENT_BINARY}}
      - rm -rf {{.LOG_DIR}}
      - rm -f {{.TEMP_FILE}}

  build-server:
    desc: Build server
    cmds:
      - go build -o {{.SERVER_BINARY}} ./cmd/server/
    sources:
      - "**/*.go"
    generates:
      - "{{.SERVER_BINARY}}"

  build-agent:
    desc: Build agent
    cmds:
      - go build -o {{.AGENT_BINARY}} ./cmd/agent/
    sources:
      - "**/*.go"
    generates:
      - "{{.AGENT_BINARY}}"

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  autotest:
    desc: Run autotests
    deps: 
      - build-server
      - build-agent
    cmds:
      - bash ./autotest.sh

  build:
    desc: Build all binaries
    deps: 
      - build-server
      - build-agent

  test-all:
    desc: Run all test
    cmds:
      - task test
      - task autotest
